### PR TITLE
WIP: Make CPANTS and POD::Coverage happy : )

### PR DESCRIPTION
**Pull request by ghost**
- Use MetaJSON plugin (Happy CPANTS)
- Specify minimum perl version (5.004) (Happy CPANTS)
- Add bare POD setup_installer and check_file_version methods (Happy POD::Coverage)
- Tidy up CheckChangeLog.pm
- Add .gitignore

@fayland I think there's more we should do with this PR but wanted to discuss with you before going further. Specifically, I think we need to add tests for the plugin and tidy up some more.

### CODE REVIEW

**Comment by fayland** [comment]
hi, I'm OK with that, I can give you co-maint permission if you like that. Thanks

**Comment by ghost** [comment]
@fayland Sure :) I forgot to mention this dist was assigned to me as part of the CPAN PR Challenge. 

Please don't do a release on this until we get some more test units in place.

**Comment by fayland** [comment]
OK, don't forget to update the Changes. 👍

**Comment by ghost** [comment]
@fayland will do my friend : )

**Pull request merged**
